### ISSUE TITLE
HW GL_SELECT does not support draw mode GL_LINES_ADJACENCY

### ISSUE THREAD

**Issue by hsanjuan** [SearchAndRescue2/sar2#44]
I have no idea what this means or how GL_LINES_ADJACENCY gets used (or now to switch for something else), but this happens on my laptop and causes a rendering mess from the moment ground-contact-check is performed.

**Comment by jmbau** [comment]
I have the _HW GL_SELECT does not support draw mode GL_LINES_ADJACENCY_ error too, but without any ghosting issue. **This seems to have appeared since I updated my Linux distro 2 weeks ago.**

My hardware / software:
AMD Radeon RX 5600 XT (navi10, LLVM 15.0.6, DRM 3.52, 6.4.9-desktop-4.mga9)
OpenGL Version 4.6.1

**Comment by jmbau** [comment]
I have the same _HW GL_SELECT does not support..._ issue with an other openGL old game since my distro update.

I suppose that explanation is here: [https://docs.gl/](https://docs.gl/) => glRenderMode is not more available in gl4.
glRenderMode function was in [https://www.khronos.org/files/opengl42-quick-reference-card.pdf](https://www.khronos.org/files/opengl42-quick-reference-card.pdf), but disappears of [https://www.khronos.org/files/opengl43-quick-reference-card.pdf](https://www.khronos.org/files/opengl43-quick-reference-card.pdf).

Related discussion here: [https://community.khronos.org/t/pick-in-opengl-4-since-gl-select-seems-deprecated/104991](https://community.khronos.org/t/pick-in-opengl-4-since-gl-select-seems-deprecated/104991) .

I can't help more...

**Comment by jmbau** [comment]
I'm not sure that it will help you, but it will maybe give you some reasons to hope: the `HW GL_SELECT does not support draw mode GL_LINES_ADJACENCY`  message when playing Sar2 has suddenly disappears when my distro has updated mesa from 23.1.5 to 24.1.4 a few weeks ago.

I don't know what it returned before, but now, `glxinfo` says:
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon RX 5600 XT (radeonsi, navi10, LLVM 15.0.6, DRM 3.54, 6.6.43-desktop-1.mga9) (0x731f)
    Version: 24.1.4
    Accelerated: yes
    Video memory: 6144MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 5346 MB, largest block: 5346 MB
    VBO free aux. memory - total: 7791 MB, largest block: 7791 MB
    Texture free memory - total: 5346 MB, largest block: 5346 MB
    Texture free aux. memory - total: 7791 MB, largest block: 7791 MB
    Renderbuffer free memory - total: 5346 MB, largest block: 5346 MB
    Renderbuffer free aux. memory - total: 7791 MB, largest block: 7791 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 6144 MB
    Total available memory: 14094 MB
    Currently available dedicated video memory: 5346 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon RX 5600 XT (radeonsi, navi10, LLVM 15.0.6, DRM 3.54, 6.6.43-desktop-1.mga9)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.1.4
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```
My other openGL old game works now fine too....
